from __future__ import annotations

import json

import httpx

from app.config import get_settings


SYSTEM_PROMPT = (
    "You are an AI clinical decision-support assistant. "
    "Generate a structured medical imaging report based on model predictions. "
    "Be clear, cautious, and emphasize that this is AI-assisted and not a diagnosis. "
    "Use professional radiology-style language."
)


def _findings_for_class(predicted_class: str) -> tuple[str, str, str]:
    label = predicted_class.upper()
    if label == "PNEUMONIA":
        return (
            "Chest radiograph (AI triage)",
            "Increased opacity patterns consistent with possible infectious infiltrate.",
            "AI model suggests possible pneumonia findings on a chest study.",
        )
    if label == "NORMAL":
        return (
            "Chest radiograph (AI triage)",
            "No dominant radiographic features suggestive of pneumonia were highlighted by the model.",
            "AI model suggests a non-pneumonia chest appearance.",
        )
    if label == "BONE_FRACTURE":
        return (
            "Musculoskeletal radiograph (AI triage)",
            "Image features are more consistent with a bone/musculoskeletal X-ray than a chest pneumonia study. "
            "Possible fracture-related patterns were highlighted by the model.",
            "AI model suggests this study is out of chest-pneumonia scope and resembles a bone fracture X-ray.",
        )
    if label == "BRAIN_NORMAL":
        return (
            "Brain imaging (AI triage)",
            "Study recognized as brain imaging. No dominant tumor-like pattern was highlighted by the model.",
            "AI model suggests brain imaging without a highlighted tumor pattern.",
        )
    if label == "BRAIN_TUMOR":
        return (
            "Brain imaging (AI triage)",
            "Study recognized as brain imaging with patterns that can be associated with intracranial tumor.",
            "AI model suggests possible brain tumor-related findings. Urgent clinical correlation is advised.",
        )
    return (
        "Medical image (AI triage)",
        "The uploaded study does not clearly match the supported chest pneumonia categories.",
        f"AI model predicted {predicted_class}.",
    )


def _template_report(
    predicted_class: str,
    confidence: float,
    probabilities: dict[str, float],
    filename: str,
) -> str:
    prob_lines = "\n".join(
        f"- {label}: {prob * 100:.1f}%" for label, prob in sorted(probabilities.items(), key=lambda x: -x[1])
    )
    modality, findings, impression = _findings_for_class(predicted_class)
    return f"""AI-ASSISTED MEDICAL IMAGING REPORT
===================================

Study: {filename}
Modality: {modality}

FINDINGS
--------
{findings}

MODEL OUTPUT
------------
Predicted class: {predicted_class}
Confidence: {confidence * 100:.1f}%
Class probabilities:
{prob_lines}

IMPRESSION
----------
{impression}

SCOPE NOTE
----------
Supported triage classes: NORMAL (chest), PNEUMONIA (chest), BONE_FRACTURE,
BRAIN_NORMAL, BRAIN_TUMOR.
This is decision support only, not a diagnosis.

DISCLAIMER
----------
This report is generated by an AI system for decision support only.
It is not a medical diagnosis. Clinical correlation and licensed
clinician review are required before any clinical action.
"""


async def generate_medical_report(
    predicted_class: str,
    confidence: float,
    probabilities: dict[str, float],
    filename: str,
) -> tuple[str, str]:
    """Return (report_text, source) where source is 'llm' or 'template'."""
    settings = get_settings()
    if not settings.openai_api_key:
        return _template_report(predicted_class, confidence, probabilities, filename), "template"

    user_prompt = (
        f"Image filename: {filename}\n"
        f"Predicted class: {predicted_class}\n"
        f"Confidence: {confidence:.4f}\n"
        f"Probabilities: {json.dumps(probabilities)}\n\n"
        "Write a concise AI-assisted imaging report with sections: "
        "Findings, Model Output, Impression, Scope Note, and Disclaimer. "
        "If class is BONE_FRACTURE, clearly state this is not a chest-pneumonia study."
    )

    headers = {
        "Authorization": f"Bearer {settings.openai_api_key}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": settings.openai_model,
        "temperature": 0.3,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ],
    }

    try:
        async with httpx.AsyncClient(base_url=settings.openai_base_url, timeout=45.0) as client:
            response = await client.post("/chat/completions", headers=headers, json=payload)
            response.raise_for_status()
            data = response.json()
            text = data["choices"][0]["message"]["content"].strip()
            if text:
                return text, "llm"
    except Exception:
        pass

    return _template_report(predicted_class, confidence, probabilities, filename), "template"
